site_name: Pywedge documentation
nav:
  - Home: index.md
  - Modules: modules.md
  - Examples: examples.md
  - License: license.md

repo_url: https://github.com/taknev83/pywedge
theme: readthedocs
